// GENERATED by `pnpm gen:scripts` (scripts/gen-script-index.ts). Do not edit.
import * as m0 from './neutral/a-super-successful-event';
import * as m1 from './neutral/bullet-bike';
import * as m2 from './neutral/dutiful-steed';
import * as m3 from './neutral/forth-into-the-great-age-of-agriculture';
import * as m4 from './neutral/hungry-for-a-miracle';
import * as m5 from './neutral/progenitors-and-guides';
import * as m6 from './neutral/quixotic-adventurer';
import * as m7 from './neutral/rivaylian-bandit';
import * as m8 from './neutral/vagabond-lizard';
import * as m9 from './neutral/wandering-chef';
import * as m10 from './forestcraft/amataz-fairy-blader';
import * as m11 from './forestcraft/amataz-reverse-blader';
import * as m12 from './forestcraft/aria-miasma-fairy';
import * as m13 from './forestcraft/arisa';
import * as m14 from './forestcraft/blessed-fairy-dancer';
import * as m15 from './forestcraft/c-c-woodland-witch';
import * as m16 from './forestcraft/cynthia-the-queen-s-blade';
import * as m17 from './forestcraft/fairy-circle';
import * as m18 from './forestcraft/fairy-slugger';
import * as m19 from './forestcraft/feybolt-archer';
import * as m20 from './forestcraft/flower-of-fairies';
import * as m21 from './forestcraft/intertwined-resolve';
import * as m22 from './forestcraft/marvelous-sunday';
import * as m23 from './forestcraft/piercye-queen-of-frost';
import * as m24 from './forestcraft/smart-falcon';
import * as m25 from './forestcraft/spinaria-wavering-will';
import * as m26 from './forestcraft/spiritshine';
import * as m27 from './forestcraft/sukuna-brave-and-small';
import * as m28 from './forestcraft/titania-s-sanctuary';
import * as m29 from './forestcraft/tree-of-wonders';
import * as m30 from './swordcraft/aurelia-blooming-blade';
import * as m31 from './swordcraft/bunny-baron-specter-duo';
import * as m32 from './swordcraft/celia-hope-s-strategist';
import * as m33 from './swordcraft/celia-sky-commander';
import * as m34 from './swordcraft/leod-the-crescent-blade';
import * as m35 from './swordcraft/nagi-hisakawa';
import * as m36 from './swordcraft/naht-s-henchman';
import * as m37 from './swordcraft/nahtnaught-cursed-queen';
import * as m38 from './swordcraft/outlaw-gunner';
import * as m39 from './swordcraft/outrunning-the-encroaching-heat';
import * as m40 from './swordcraft/radical-gunslinger';
import * as m41 from './swordcraft/ralmia-sonic-racer';
import * as m42 from './swordcraft/shield-guardian';
import * as m43 from './swordcraft/trial-initiation';
import * as m44 from './swordcraft/tyrant-s-order';
import * as m45 from './swordcraft/unbridled-fury';
import * as m46 from './swordcraft/val-trusty-getaway-car';
import * as m47 from './runecraft/agnes-tachyon';
import * as m48 from './runecraft/cheval-grand';
import * as m49 from './runecraft/daiwa-scarlet';
import * as m50 from './runecraft/lamplit-training-of-a-witch-to-be';
import * as m51 from './runecraft/lucky-star-in-the-sky';
import * as m52 from './runecraft/make-some-noise';
import * as m53 from './runecraft/sweep-tosho';
import * as m54 from './runecraft/vodka';
import * as m55 from './dragoncraft/pious-flame-heavens-scorcher';
import * as m56 from './dragoncraft/special-week-the-brightest-star-in-japan';
import * as m57 from './abysscraft/7-more-centimeters';
import * as m58 from './abysscraft/air-shakur';
import * as m59 from './abysscraft/hishi-miracle';
import * as m60 from './abysscraft/manhattan-cafe';
import * as m61 from './abysscraft/matikanetannhauser-machitan-adventure';
import * as m62 from './abysscraft/my-solo-drawn-to-raindrop-drums';

export const SCRIPT_FILES: readonly string[] = [
  'neutral/a-super-successful-event',
  'neutral/bullet-bike',
  'neutral/dutiful-steed',
  'neutral/forth-into-the-great-age-of-agriculture',
  'neutral/hungry-for-a-miracle',
  'neutral/progenitors-and-guides',
  'neutral/quixotic-adventurer',
  'neutral/rivaylian-bandit',
  'neutral/vagabond-lizard',
  'neutral/wandering-chef',
  'forestcraft/amataz-fairy-blader',
  'forestcraft/amataz-reverse-blader',
  'forestcraft/aria-miasma-fairy',
  'forestcraft/arisa',
  'forestcraft/blessed-fairy-dancer',
  'forestcraft/c-c-woodland-witch',
  'forestcraft/cynthia-the-queen-s-blade',
  'forestcraft/fairy-circle',
  'forestcraft/fairy-slugger',
  'forestcraft/feybolt-archer',
  'forestcraft/flower-of-fairies',
  'forestcraft/intertwined-resolve',
  'forestcraft/marvelous-sunday',
  'forestcraft/piercye-queen-of-frost',
  'forestcraft/smart-falcon',
  'forestcraft/spinaria-wavering-will',
  'forestcraft/spiritshine',
  'forestcraft/sukuna-brave-and-small',
  'forestcraft/titania-s-sanctuary',
  'forestcraft/tree-of-wonders',
  'swordcraft/aurelia-blooming-blade',
  'swordcraft/bunny-baron-specter-duo',
  'swordcraft/celia-hope-s-strategist',
  'swordcraft/celia-sky-commander',
  'swordcraft/leod-the-crescent-blade',
  'swordcraft/nagi-hisakawa',
  'swordcraft/naht-s-henchman',
  'swordcraft/nahtnaught-cursed-queen',
  'swordcraft/outlaw-gunner',
  'swordcraft/outrunning-the-encroaching-heat',
  'swordcraft/radical-gunslinger',
  'swordcraft/ralmia-sonic-racer',
  'swordcraft/shield-guardian',
  'swordcraft/trial-initiation',
  'swordcraft/tyrant-s-order',
  'swordcraft/unbridled-fury',
  'swordcraft/val-trusty-getaway-car',
  'runecraft/agnes-tachyon',
  'runecraft/cheval-grand',
  'runecraft/daiwa-scarlet',
  'runecraft/lamplit-training-of-a-witch-to-be',
  'runecraft/lucky-star-in-the-sky',
  'runecraft/make-some-noise',
  'runecraft/sweep-tosho',
  'runecraft/vodka',
  'dragoncraft/pious-flame-heavens-scorcher',
  'dragoncraft/special-week-the-brightest-star-in-japan',
  'abysscraft/7-more-centimeters',
  'abysscraft/air-shakur',
  'abysscraft/hishi-miracle',
  'abysscraft/manhattan-cafe',
  'abysscraft/matikanetannhauser-machitan-adventure',
  'abysscraft/my-solo-drawn-to-raindrop-drums',
];

export const SCRIPT_MODULES: readonly Record<string, unknown>[] = [
  m0,
  m1,
  m2,
  m3,
  m4,
  m5,
  m6,
  m7,
  m8,
  m9,
  m10,
  m11,
  m12,
  m13,
  m14,
  m15,
  m16,
  m17,
  m18,
  m19,
  m20,
  m21,
  m22,
  m23,
  m24,
  m25,
  m26,
  m27,
  m28,
  m29,
  m30,
  m31,
  m32,
  m33,
  m34,
  m35,
  m36,
  m37,
  m38,
  m39,
  m40,
  m41,
  m42,
  m43,
  m44,
  m45,
  m46,
  m47,
  m48,
  m49,
  m50,
  m51,
  m52,
  m53,
  m54,
  m55,
  m56,
  m57,
  m58,
  m59,
  m60,
  m61,
  m62,
];
