// GENERATED by `pnpm gen:scripts` (scripts/gen-script-index.ts). Do not edit.
import * as m0 from './neutral/a-super-successful-event';
import * as m1 from './neutral/alice-golden-afternoon';
import * as m2 from './neutral/apollo-heaven-s-envoy';
import * as m3 from './neutral/assembly-droid';
import * as m4 from './neutral/at-the-end-of-the-day';
import * as m5 from './neutral/bullet-bike';
import * as m6 from './neutral/dutiful-steed';
import * as m7 from './neutral/feena-dynamite-daredevil';
import * as m8 from './neutral/forth-into-the-great-age-of-agriculture';
import * as m9 from './neutral/hoverboard-mercenary';
import * as m10 from './neutral/hungry-for-a-miracle';
import * as m11 from './neutral/mechagun-wielder';
import * as m12 from './neutral/progenitors-and-guides';
import * as m13 from './neutral/quixotic-adventurer';
import * as m14 from './neutral/repair-mode';
import * as m15 from './neutral/rivaylian-bandit';
import * as m16 from './neutral/vagabond-lizard';
import * as m17 from './neutral/wandering-chef';
import * as m18 from './neutral/workshop-farmers-for-a-day';
import * as m19 from './forestcraft/a-more-marvelous-world';
import * as m20 from './forestcraft/amataz-fairy-blader';
import * as m21 from './forestcraft/amataz-reverse-blader';
import * as m22 from './forestcraft/anastasia';
import * as m23 from './forestcraft/aria-miasma-fairy';
import * as m24 from './forestcraft/arisa-evergreen-arrow';
import * as m25 from './forestcraft/arisa';
import * as m26 from './forestcraft/blessed-fairy-dancer';
import * as m27 from './forestcraft/c-c-woodland-witch';
import * as m28 from './forestcraft/cheshire-cat';
import * as m29 from './forestcraft/chipper-skipper';
import * as m30 from './forestcraft/cynthia-the-queen-s-blade';
import * as m31 from './forestcraft/fairy-circle';
import * as m32 from './forestcraft/fairy-slugger';
import * as m33 from './forestcraft/feybolt-archer';
import * as m34 from './forestcraft/flower-of-fairies';
import * as m35 from './forestcraft/forest-guardian-s-bow';
import * as m36 from './forestcraft/gale-arrow';
import * as m37 from './forestcraft/haru-urara-sunny-passion';
import * as m38 from './forestcraft/hokko-tarumae';
import * as m39 from './forestcraft/intertwined-resolve';
import * as m40 from './forestcraft/lycoris-soothing-venom';
import * as m41 from './forestcraft/marvelous-sunday';
import * as m42 from './forestcraft/minami-nitta-water-s-edge-bride';
import * as m43 from './forestcraft/nature-s-guidance';
import * as m44 from './forestcraft/piercye-queen-of-frost';
import * as m45 from './forestcraft/resolve-of-the-nine-tailed-fox';
import * as m46 from './forestcraft/sakura-bakushin-o';
import * as m47 from './forestcraft/salvia-panther';
import * as m48 from './forestcraft/sekka-fatebound-fox';
import * as m49 from './forestcraft/sekka-ninefold-blaze';
import * as m50 from './forestcraft/shamu-shama-posh-felines';
import * as m51 from './forestcraft/smart-falcon';
import * as m52 from './forestcraft/sounds-of-earth';
import * as m53 from './forestcraft/spinaria-wavering-will';
import * as m54 from './forestcraft/spiritshine';
import * as m55 from './forestcraft/storm-arrow';
import * as m56 from './forestcraft/sukuna-brave-and-small';
import * as m57 from './forestcraft/titania-s-sanctuary';
import * as m58 from './forestcraft/tree-of-wonders';
import * as m59 from './forestcraft/windflower-tiger';
import * as m60 from './swordcraft/aurelia-blooming-blade';
import * as m61 from './swordcraft/bunny-baron-specter-duo';
import * as m62 from './swordcraft/celia-hope-s-strategist';
import * as m63 from './swordcraft/celia-sky-commander';
import * as m64 from './swordcraft/leod-the-crescent-blade';
import * as m65 from './swordcraft/nagi-hisakawa';
import * as m66 from './swordcraft/naht-s-henchman';
import * as m67 from './swordcraft/nahtnaught-cursed-queen';
import * as m68 from './swordcraft/outlaw-gunner';
import * as m69 from './swordcraft/outrunning-the-encroaching-heat';
import * as m70 from './swordcraft/radical-gunslinger';
import * as m71 from './swordcraft/ralmia-sonic-racer';
import * as m72 from './swordcraft/shield-guardian';
import * as m73 from './swordcraft/sirius-symboli-escorte-etoile';
import * as m74 from './swordcraft/trial-initiation';
import * as m75 from './swordcraft/tyrant-s-order';
import * as m76 from './swordcraft/unbridled-fury';
import * as m77 from './swordcraft/val-trusty-getaway-car';
import * as m78 from './runecraft/agnes-tachyon';
import * as m79 from './runecraft/anne-grea-bonds-everlasting';
import * as m80 from './runecraft/chain-lightning';
import * as m81 from './runecraft/chakram-wizard';
import * as m82 from './runecraft/chaos-wielder';
import * as m83 from './runecraft/cheval-grand';
import * as m84 from './runecraft/crystal-fencer';
import * as m85 from './runecraft/daiwa-scarlet';
import * as m86 from './runecraft/daria-infinity-witch';
import * as m87 from './runecraft/dimension-shift';
import * as m88 from './runecraft/grimoire-sorcerer';
import * as m89 from './runecraft/lamplit-training-of-a-witch-to-be';
import * as m90 from './runecraft/lucky-star-in-the-sky';
import * as m91 from './runecraft/make-some-noise';
import * as m92 from './runecraft/melvie-princess-witch';
import * as m93 from './runecraft/mr-bertrand-magic-mentor';
import * as m94 from './runecraft/mysterian-knowledge';
import * as m95 from './runecraft/mysterian-missile';
import * as m96 from './runecraft/mystic-absorption';
import * as m97 from './runecraft/riven-earth';
import * as m98 from './runecraft/scorching-blast';
import * as m99 from './runecraft/story-of-a-lifetime';
import * as m100 from './runecraft/sweep-tosho';
import * as m101 from './runecraft/truth-s-adjudication';
import * as m102 from './runecraft/vodka';
import * as m103 from './runecraft/witchbolt';
import * as m104 from './runecraft/yukishima-master-biographer';
import * as m105 from './dragoncraft/katsuragi-ace';
import * as m106 from './dragoncraft/pious-flame-heavens-scorcher';
import * as m107 from './dragoncraft/special-week-the-brightest-star-in-japan';
import * as m108 from './abysscraft/7-more-centimeters';
import * as m109 from './abysscraft/aenea-amethyst-rebel';
import * as m110 from './abysscraft/aenea-creative-amethyst';
import * as m111 from './abysscraft/air-shakur';
import * as m112 from './abysscraft/alpha-drive';
import * as m113 from './abysscraft/duramente';
import * as m114 from './abysscraft/friends-forever';
import * as m115 from './abysscraft/garnet-waltz';
import * as m116 from './abysscraft/hishi-miracle';
import * as m117 from './abysscraft/lelouch-lamperouge';
import * as m118 from './abysscraft/manhattan-cafe';
import * as m119 from './abysscraft/matikanetannhauser-machitan-adventure';
import * as m120 from './abysscraft/mayano-top-gun';
import * as m121 from './abysscraft/mono-garnet-rebel';
import * as m122 from './abysscraft/mono-immortal-garnet';
import * as m123 from './abysscraft/my-solo-drawn-to-raindrop-drums';
import * as m124 from './abysscraft/nicola-enduring-steward';
import * as m125 from './abysscraft/nicola-forbidden-strength';
import * as m126 from './abysscraft/roly-poly-mk-i';
import * as m127 from './abysscraft/roly-poly-mk-ii';
import * as m128 from './abysscraft/steeled-hopes';
import * as m129 from './abysscraft/twin-turbo-turbo-booooost';
import * as m130 from './havencraft/jungle-pocket';
import * as m131 from './havencraft/the-will-to-overtake';

export const SCRIPT_FILES: readonly string[] = [
  'neutral/a-super-successful-event',
  'neutral/alice-golden-afternoon',
  'neutral/apollo-heaven-s-envoy',
  'neutral/assembly-droid',
  'neutral/at-the-end-of-the-day',
  'neutral/bullet-bike',
  'neutral/dutiful-steed',
  'neutral/feena-dynamite-daredevil',
  'neutral/forth-into-the-great-age-of-agriculture',
  'neutral/hoverboard-mercenary',
  'neutral/hungry-for-a-miracle',
  'neutral/mechagun-wielder',
  'neutral/progenitors-and-guides',
  'neutral/quixotic-adventurer',
  'neutral/repair-mode',
  'neutral/rivaylian-bandit',
  'neutral/vagabond-lizard',
  'neutral/wandering-chef',
  'neutral/workshop-farmers-for-a-day',
  'forestcraft/a-more-marvelous-world',
  'forestcraft/amataz-fairy-blader',
  'forestcraft/amataz-reverse-blader',
  'forestcraft/anastasia',
  'forestcraft/aria-miasma-fairy',
  'forestcraft/arisa-evergreen-arrow',
  'forestcraft/arisa',
  'forestcraft/blessed-fairy-dancer',
  'forestcraft/c-c-woodland-witch',
  'forestcraft/cheshire-cat',
  'forestcraft/chipper-skipper',
  'forestcraft/cynthia-the-queen-s-blade',
  'forestcraft/fairy-circle',
  'forestcraft/fairy-slugger',
  'forestcraft/feybolt-archer',
  'forestcraft/flower-of-fairies',
  'forestcraft/forest-guardian-s-bow',
  'forestcraft/gale-arrow',
  'forestcraft/haru-urara-sunny-passion',
  'forestcraft/hokko-tarumae',
  'forestcraft/intertwined-resolve',
  'forestcraft/lycoris-soothing-venom',
  'forestcraft/marvelous-sunday',
  'forestcraft/minami-nitta-water-s-edge-bride',
  'forestcraft/nature-s-guidance',
  'forestcraft/piercye-queen-of-frost',
  'forestcraft/resolve-of-the-nine-tailed-fox',
  'forestcraft/sakura-bakushin-o',
  'forestcraft/salvia-panther',
  'forestcraft/sekka-fatebound-fox',
  'forestcraft/sekka-ninefold-blaze',
  'forestcraft/shamu-shama-posh-felines',
  'forestcraft/smart-falcon',
  'forestcraft/sounds-of-earth',
  'forestcraft/spinaria-wavering-will',
  'forestcraft/spiritshine',
  'forestcraft/storm-arrow',
  'forestcraft/sukuna-brave-and-small',
  'forestcraft/titania-s-sanctuary',
  'forestcraft/tree-of-wonders',
  'forestcraft/windflower-tiger',
  'swordcraft/aurelia-blooming-blade',
  'swordcraft/bunny-baron-specter-duo',
  'swordcraft/celia-hope-s-strategist',
  'swordcraft/celia-sky-commander',
  'swordcraft/leod-the-crescent-blade',
  'swordcraft/nagi-hisakawa',
  'swordcraft/naht-s-henchman',
  'swordcraft/nahtnaught-cursed-queen',
  'swordcraft/outlaw-gunner',
  'swordcraft/outrunning-the-encroaching-heat',
  'swordcraft/radical-gunslinger',
  'swordcraft/ralmia-sonic-racer',
  'swordcraft/shield-guardian',
  'swordcraft/sirius-symboli-escorte-etoile',
  'swordcraft/trial-initiation',
  'swordcraft/tyrant-s-order',
  'swordcraft/unbridled-fury',
  'swordcraft/val-trusty-getaway-car',
  'runecraft/agnes-tachyon',
  'runecraft/anne-grea-bonds-everlasting',
  'runecraft/chain-lightning',
  'runecraft/chakram-wizard',
  'runecraft/chaos-wielder',
  'runecraft/cheval-grand',
  'runecraft/crystal-fencer',
  'runecraft/daiwa-scarlet',
  'runecraft/daria-infinity-witch',
  'runecraft/dimension-shift',
  'runecraft/grimoire-sorcerer',
  'runecraft/lamplit-training-of-a-witch-to-be',
  'runecraft/lucky-star-in-the-sky',
  'runecraft/make-some-noise',
  'runecraft/melvie-princess-witch',
  'runecraft/mr-bertrand-magic-mentor',
  'runecraft/mysterian-knowledge',
  'runecraft/mysterian-missile',
  'runecraft/mystic-absorption',
  'runecraft/riven-earth',
  'runecraft/scorching-blast',
  'runecraft/story-of-a-lifetime',
  'runecraft/sweep-tosho',
  'runecraft/truth-s-adjudication',
  'runecraft/vodka',
  'runecraft/witchbolt',
  'runecraft/yukishima-master-biographer',
  'dragoncraft/katsuragi-ace',
  'dragoncraft/pious-flame-heavens-scorcher',
  'dragoncraft/special-week-the-brightest-star-in-japan',
  'abysscraft/7-more-centimeters',
  'abysscraft/aenea-amethyst-rebel',
  'abysscraft/aenea-creative-amethyst',
  'abysscraft/air-shakur',
  'abysscraft/alpha-drive',
  'abysscraft/duramente',
  'abysscraft/friends-forever',
  'abysscraft/garnet-waltz',
  'abysscraft/hishi-miracle',
  'abysscraft/lelouch-lamperouge',
  'abysscraft/manhattan-cafe',
  'abysscraft/matikanetannhauser-machitan-adventure',
  'abysscraft/mayano-top-gun',
  'abysscraft/mono-garnet-rebel',
  'abysscraft/mono-immortal-garnet',
  'abysscraft/my-solo-drawn-to-raindrop-drums',
  'abysscraft/nicola-enduring-steward',
  'abysscraft/nicola-forbidden-strength',
  'abysscraft/roly-poly-mk-i',
  'abysscraft/roly-poly-mk-ii',
  'abysscraft/steeled-hopes',
  'abysscraft/twin-turbo-turbo-booooost',
  'havencraft/jungle-pocket',
  'havencraft/the-will-to-overtake',
];

export const SCRIPT_MODULES: readonly Record<string, unknown>[] = [
  m0,
  m1,
  m2,
  m3,
  m4,
  m5,
  m6,
  m7,
  m8,
  m9,
  m10,
  m11,
  m12,
  m13,
  m14,
  m15,
  m16,
  m17,
  m18,
  m19,
  m20,
  m21,
  m22,
  m23,
  m24,
  m25,
  m26,
  m27,
  m28,
  m29,
  m30,
  m31,
  m32,
  m33,
  m34,
  m35,
  m36,
  m37,
  m38,
  m39,
  m40,
  m41,
  m42,
  m43,
  m44,
  m45,
  m46,
  m47,
  m48,
  m49,
  m50,
  m51,
  m52,
  m53,
  m54,
  m55,
  m56,
  m57,
  m58,
  m59,
  m60,
  m61,
  m62,
  m63,
  m64,
  m65,
  m66,
  m67,
  m68,
  m69,
  m70,
  m71,
  m72,
  m73,
  m74,
  m75,
  m76,
  m77,
  m78,
  m79,
  m80,
  m81,
  m82,
  m83,
  m84,
  m85,
  m86,
  m87,
  m88,
  m89,
  m90,
  m91,
  m92,
  m93,
  m94,
  m95,
  m96,
  m97,
  m98,
  m99,
  m100,
  m101,
  m102,
  m103,
  m104,
  m105,
  m106,
  m107,
  m108,
  m109,
  m110,
  m111,
  m112,
  m113,
  m114,
  m115,
  m116,
  m117,
  m118,
  m119,
  m120,
  m121,
  m122,
  m123,
  m124,
  m125,
  m126,
  m127,
  m128,
  m129,
  m130,
  m131,
];
