/**
 * Rebuilds packages/cards/src/scripts.generated.ts: one import per card script file, found by
 * walking `<craft>/<card>.ts`. Adding a card is "create the file, run this", never "edit a list".
 *
 *   pnpm gen:scripts
 *
 * `packages/cards/src/layout.test.ts` fails when the committed index is stale.
 */
/// <reference types="node" />
import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CRAFT_DIRS } from '../packages/cards/src/crafts';

const SRC = join(dirname(fileURLToPath(import.meta.url)), '../packages/cards/src');

const files: string[] = [];
for (const craft of CRAFT_DIRS) {
  const dir = join(SRC, craft);
  if (!existsSync(dir)) continue;
  for (const name of readdirSync(dir).sort()) {
    if (name.endsWith('.ts') && !name.endsWith('.test.ts'))
      files.push(`${craft}/${name.slice(0, -3)}`);
  }
}

const out = [
  '// GENERATED by `pnpm gen:scripts` (scripts/gen-script-index.ts). Do not edit.',
  ...files.map((file, i) => `import * as m${i} from './${file}';`),
  '',
  'export const SCRIPT_FILES: readonly string[] = [',
  ...files.map((file) => `  '${file}',`),
  '];',
  '',
  'export const SCRIPT_MODULES: readonly Record<string, unknown>[] = [',
  ...files.map((_, i) => `  m${i},`),
  '];',
  '',
];

writeFileSync(join(SRC, 'scripts.generated.ts'), out.join('\n'));
process.stderr.write(`Indexed ${files.length} card scripts\n`);
