import { cardKey, type CardDefinition } from '../model/cards';
import { asCardDefId } from '../model/ids';

const token = (
  name: string,
  spec: Pick<
    CardDefinition,
    'kind' | 'cardClass' | 'cost' | 'attack' | 'defense' | 'traits' | 'keywords' | 'text'
  >,
): CardDefinition => ({
  id: asCardDefId(`token:${name.replace(/\s+/g, '')}`),
  key: cardKey(name, 'token'),
  name,
  special: 'token',
  universe: null,
  artUrl: null,
  ...spec,
});

/** Appendix A prototypes plus tokens the live Swordcraft dump summons. */
export const DEFAULT_TOKENS: Readonly<Record<string, CardDefinition>> = {
  Fairy: token('Fairy', {
    kind: 'follower',
    cardClass: 'forestcraft',
    traits: ['Pixie'],
    cost: 1,
    attack: 1,
    defense: 1,
    keywords: [],
    text: '',
  }),
  'Fairy Wisp': token('Fairy Wisp', {
    kind: 'follower',
    cardClass: 'forestcraft',
    traits: ['Pixie'],
    cost: 0,
    attack: 1,
    defense: 1,
    keywords: [],
    text: '',
  }),
  'Shield Guardian': token('Shield Guardian', {
    kind: 'follower',
    cardClass: 'swordcraft',
    traits: ['Officer'],
    cost: 1,
    attack: 1,
    defense: 1,
    keywords: ['ward'],
    text: 'Ward.',
  }),
  'Bullet Bike': token('Bullet Bike', {
    kind: 'amulet',
    cardClass: 'neutral',
    traits: ['Wasteland', 'Mount'],
    cost: 1,
    attack: null,
    defense: null,
    keywords: [],
    text: "[act]\nBury this card: Select a follower on your field. Give it Rush and, if it's a\nWasteland follower, [attack]+1.",
  }),
  'Dutiful Steed': token('Dutiful Steed', {
    kind: 'amulet',
    cardClass: 'neutral',
    traits: ['Wasteland', 'Mount', 'Beast'],
    cost: 1,
    attack: null,
    defense: null,
    keywords: [],
    text: "[act]\nBury this card: Select a follower on your field and, if it's a Wasteland\nfollower, give it [attack]+1/[defense]+1.",
  }),
  'Val, Trusty Getaway Car': token('Val, Trusty Getaway Car', {
    kind: 'amulet',
    cardClass: 'swordcraft',
    traits: ['Wasteland', 'Mount'],
    cost: 2,
    attack: null,
    defense: null,
    keywords: ['strike', 'storm'],
    text: "[act]\n[engage] a Bunny & Baron, Specter Duo on your field:\nManeuver this card. (For the rest of this turn, it becomes a follower with\n[attack]3/[defense]3.)\n[act]\n[cost01], [engage] 2 followers on your field:\nManeuver this card.\nStorm.\nStrike - If there's another Wasteland follower on your field, draw a card.",
  }),
  'Assembly Droid': token('Assembly Droid', {
    kind: 'follower',
    cardClass: 'neutral',
    traits: ['Machina'],
    cost: 1,
    attack: 1,
    defense: 1,
    keywords: [],
    text: 'act engage, bury 3 Machina followers: Select an enemy follower on the field and deal it 5 damage.',
  }),
  'Repair Mode': token('Repair Mode', {
    kind: 'spell',
    cardClass: 'neutral',
    traits: ['Machina'],
    cost: 1,
    attack: null,
    defense: null,
    keywords: ['quick'],
    text: 'quick\nGive your leader defense+1.',
  }),
  'Gale Arrow': token('Gale Arrow', {
    kind: 'spell',
    cardClass: 'forestcraft',
    traits: ['Elf'],
    cost: 1,
    attack: null,
    defense: null,
    keywords: [],
    text: 'Select an enemy follower on the field. Combo (3) - Deal it 2 damage.',
  }),
  'Storm Arrow': token('Storm Arrow', {
    kind: 'spell',
    cardClass: 'forestcraft',
    traits: ['Elf'],
    cost: 1,
    attack: null,
    defense: null,
    keywords: [],
    text: 'Combo (5) - Deal 2 damage to each enemy leader.',
  }),
  'Mysterian Missile': token('Mysterian Missile', {
    kind: 'spell',
    cardClass: 'runecraft',
    traits: ['Mage', 'Academic'],
    cost: 2,
    attack: null,
    defense: null,
    keywords: [],
    text: 'Select an enemy follower on the field and deal it 3 damage. If there are at least 10 Academic cards in your cemetery, deal 2 damage to its leader.',
  }),
};
